name: Deploy to Google Cloud Run using deploy.sh

on:
  push:
    branches:
      - main
    paths:
      - deploy.sh
      - .github/workflows/deploy.yml
      - image_processor_func/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GCF_FUNCTION_NAME_ENV_VAR: ${{ secrets.GCF_FUNCTION_NAME_ENV_VAR }}
      GCF_REGION_ENV_VAR: ${{ secrets.GCF_REGION_ENV_VAR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Make deploy script executable
        run: chmod +x ./deploy.sh

      - name: Deploy to Cloud Functions using script
        run: ./deploy.sh
