name: Deploy to Google Cloud Functions using deploy.sh

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GCF_FUNCTION_NAME_ENV_VAR: ${{ secrets.GCF_FUNCTION_NAME }}
      GCF_REGION_ENV_VAR: ${{ secrets.GCF_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Make deploy script executable
        run: chmod +x ./deploy.sh

      - name: Deploy to Cloud Functions using script
        run: ./deploy.sh